// Generated by GitHub Copilot
/**
 * Local runtime configuration template for Learning Easy.
 *
 * SETUP:
 *   1. Copy this file to `config.js` (in the same directory).
 *   2. Replace the empty string below with your Gemini API key.
 *   3. Save. Reload the app — AI features will activate automatically.
 *
 * The real `config.js` is listed in .gitignore and must NEVER be committed.
 *
 * Get a free API key: https://aistudio.google.com/app/apikey
 */
window.GEMINI_API_KEY = '';
