// Generated by GitHub Copilot
/**
 * Build script for Learning Easy.
 * - Copies index.html to dist/.
 * - Copies config.js to dist/ if it exists; otherwise copies config.example.js
 *   as a placeholder so the deploy step can replace it later.
 * Run with: node scripts/build.js  (or: npm run build)
 */
const fs   = require('fs');
const path = require('path');

const root      = path.resolve(__dirname, '..');
const distDir   = path.join(root, 'dist');
const indexSrc  = path.join(root, 'index.html');
const configSrc = path.join(root, 'config.js');
const configEx  = path.join(root, 'config.example.js');

if (!fs.existsSync(distDir)) fs.mkdirSync(distDir, { recursive: true });

// Copy main HTML
fs.copyFileSync(indexSrc, path.join(distDir, 'index.html'));
const sizeKB = (fs.statSync(path.join(distDir, 'index.html')).size / 1024).toFixed(1);
console.log(`OK  index.html -> dist/index.html (${sizeKB} KB)`);

// Copy config
if (fs.existsSync(configSrc)) {
  fs.copyFileSync(configSrc, path.join(distDir, 'config.js'));
  console.log('OK  config.js  -> dist/config.js  (contains API key — keep dist/ out of public repos)');
} else if (fs.existsSync(configEx)) {
  fs.copyFileSync(configEx, path.join(distDir, 'config.js'));
  console.warn('WARN config.js not found — copied config.example.js as placeholder.');
  console.warn('     AI features will be disabled until you set a real key in dist/config.js.');
} else {
  console.warn('WARN no config file found. AI features will be disabled.');
}

console.log('\nBuild complete. Deploy the contents of dist/.');

